const ProductConstants = {
  API_REQUEST: "API_REQUEST",
  API_FAIL: "API_FAIL",
  API_ERROR: "API_ERROR",

  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ONE_PRODUCT_SUCCESS: "GET_ONE_PRODUCT_SUCCESS",
};

export default ProductConstants;
